### ISSUE TITLE
Observing a promise's resolved value

### ISSUE THREAD

**Issue by alexisabril** [canjs/can-observation#10]
https://github.com/canjs/can-observation/blob/master/reader/reader.js#L284

Should detect a promise, then use `then` to get the value inside. Application: http://jsbin.com/zepaluq/1/edit?js,output

**Comment by alexisabril** [comment]
Also had a side discussion w/ @justinbmeyer on this issue. Noting that a possible syntax may be needed to define "right to left" sets, as opposed to "left to right".

The additional use case is if a resolved value is currently `undefined`, two-way binding on that value will attempt to set immediately. This is an issue since we're dealing with a promise. The map whose value needs to be set will not yet exist.

**Comment by justinbmeyer** [comment]
I think this is resolved now.
