### ISSUE TITLE
reader.write should handle nicely when it can't write to an object

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-observation#38]
Something like:

`reader.write({}, "foo.bar", "value")`

should let people know what's going on instead of throwing a weird error.  

Related to: https://github.com/donejs/bitballs/issues/274

**Comment by justinbmeyer** [comment]
this should be done as part of can-reflect.

**Comment by phillipskevin** [comment]
I think a better error is probably being given now that can-reflect has landed. This should be verified and closed.

**Comment by bgando** [comment]
![image](https://user-images.githubusercontent.com/3348231/29946579-e7857a14-8e73-11e7-9abe-505867d57b88.png)

https://jsbin.com/kivucucoza/1/edit?html,js,console,output

**Comment by phillipskevin** [comment]
Is this different from the original (pre can-reflect) error?

**Comment by bgando** [comment]
@phillipskevin - I asked @justinbmeyer and he said it was good, but I'm not sure what you had in mind. Let me know if I should re-open this issue.

**Comment by phillipskevin** [comment]
I just wasn't sure if it was different from the error that was originally given in bitballs when the issue was opened. No need to re-open now, we can re-examine this if someone brings it up again.

**Comment by bgando** [comment]
Sounds good. I can't actually read the screen capture from bitballs so I'm not sure. Also, if it comes up again, we should move this to `can-stache-key`.
