### ISSUE TITLE
API changes

### ISSUE THREAD

**Issue by matthewp** [canjs/can-observation#4]
Playing on the theme that this library is about manipulating a stack of observations.

* **module**: can-observation

* `ObserveInfo.observe(obj, event)` **->** `Observation.add(obj, event)`
* `ObserveInfo.observes(observes)` **->** `Observation.addAll(observations)`
* `ObserveInfo.notObserve(fn)` **->** `Observation.ignore(fn)`
* Keep `.trap()` named the same (can't think of a better name here).

**Comment by justinbmeyer** [comment]
I like it.

**Comment by matthewp** [comment]
Dependent modules: https://www.npmjs.com/browse/depended/can-observe-info

**Comment by matthewp** [comment]
* [ ] - can-define
* [ ] - can-connect
* [ ] - can-route
* [ ] - can-stache
* [ ] - can-view-callbacks
* [ ] - can-component
* [ ] - can-stache-bindings
* [ ] - can-view-scope
* [ ] - can-map
* [ ] - can-list
* [ ] - can-compute
* [ ] - can-simple-map

**Comment by matthewp** [comment]
This is done (finally).
