### ISSUE TITLE
observeReader.write doesn't support writing properties containing `.`s to maps

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-observation#75]
`Map`s have special rules for writing [properties with dots in the their names](http://canjs.com/doc/can-map.prototype.attr.html#Propertieswithdotsintheirname).

I think this needs to be handled here: https://github.com/canjs/can-observation/blob/master/reader/reader.js#L196

so that it does something like this
```
if (prop.indexOf('.') === -1) {
        base.attr(prop, newVal);
} else {
        base.attr({ [prop]: newVal });
}
```

**Comment by justinbmeyer** [comment]
does escaping work? `prop\.name`?

**Comment by phillipskevin** [comment]
No, not yet. It will work with https://github.com/canjs/can-observation/pull/76. You can double check that the escaping is correct in [this test](https://github.com/canjs/can-observation/pull/76/files#diff-c2f5c2e9723bf79deb862a5b7b93c8a4R143).

**Comment by justinbmeyer** [comment]
The solution to this is that `canReflect.setKeyValue` should be made to handle this right for can-maps.

**Comment by phillipskevin** [comment]
Issue moved to [canjs/can-map #65](https://github.com/canjs/can-map/issues/65) via [**ZenHub**](https://www.zenhub.com/)
