### ISSUE TITLE
3.3.0 removed reader.js

### ISSUE THREAD

**Issue by runn-vermel** [canjs/can-observation#99]
Hi there - I see that reader/reader.js was removed in version 3.3.0  - since this is breaking backwrads compatibility, this should have a 4.0.0 release.

**Comment by justinbmeyer** [comment]
Was reader documented? If it was, it shouldn't have been removed. We can polyfill it with can-stache-key. 

If something is not documented, we can change it and still be semver compliant.

**Comment by runn-vermel** [comment]
well, i have external canJS libraries calling this file, so, even if it was internal, it's used by other canJs libraries as an external resource...

**Comment by justinbmeyer** [comment]
CanJS has a lot of potentially useful internal APIs which we make to power the public features. If something is not documented, we can change it at anytime. This gives us flexibility to improve the internal mechanics. 

If your libraries depend on something else not documented, let us know and we can prioritize the API review to polish its APIs, get it into a stable place, and document it. 

I'll move this to can-stache-key and propose a finalized API.
